version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: bank-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'

  bank-app:
    container_name: bank-app
    image: maven:3.9.6-eclipse-temurin-17
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - '8081:8081'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    command: mvn spring-boot:run